### ISSUE TITLE
Canonical react-daisyui example

### ISSUE THREAD

**Issue by ChrisCates** [daisyui/daisyui-next#1]
I use this example repo with react-daisyui. With the addition of:

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['react-daisyui'],
  reactStrictMode: true,
}

module.exports = nextConfig
```

And it won't apply styles.

I noticed that you need to use the `'use client'` directive when using `react-daisyui` components.
This shouldn't be necessary nor the case. Given that the `react-daisyui` library should be applying purely class names at static runtime, therefore, should fully support SSR rendering.

**Comment by saadeghi** [comment]
This example repo is not using `react-daisyui` (React component library).  
It's using `daisyui` (the Tailwind CSS plugin)  
I'm not sure if [`react-daisyui`](https://github.com/daisyui/react-daisyui) is going to be compatible as server components, but you can ask in it's own repo: https://github.com/daisyui/react-daisyui
